### ISSUE TITLE
Mocha test failed

### ISSUE THREAD

**Issue by tnedich** [mako-taco/react-fluxthis-webpack-mocha-gulp#1]
[00:01:39] Starting 'watch'...
[00:01:39] Starting test server on port 21113
[00:01:48] Starting unit tests
[00:01:49] Error: spawn node_modules.bin\mocha-phantomjs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:349:13)
[00:01:49] Mocha exited with code ENOENT
[00:01:49] Unit tests finished
[00:01:49] Tests failed
[00:01:51] Build complete
[00:01:52] Starting unit tests
[00:01:52] Error: spawn node_modules.bin\mocha-phantomjs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:349:13)
[00:01:52] Mocha exited with code ENOENT
[00:01:52] Unit tests finished
[00:01:52] Tests failed

**Comment by mako-taco** [comment]
What OS?

**Comment by tnedich** [comment]
Win 7 Ultimate 64 bit :)

**Comment by mako-taco** [comment]
@tnedich even on windows, I cannot possibly understand how  `node_modules.bin\mocha-phantomjs`
is the result of `path.join('node_modules','.bin','mocha-phantomjs')`!

Can you verify this behavior for me? Paste this into a node REPL, started inside the root directory of the project?:

``` js
var path = require('path');
var p = path.join('node_modules','.bin','mocha-phantomjs');
console.log('The path is', p);
```

If it ends up just being an error in the gulp output, please check that path and ensure mocha-phantomjs exists in there. It's possible on windows that only a `.cmd` file is created.  If that's the case, I will add in some logic specifically for windows users.

**Comment by tnedich** [comment]
Yes I am geting this:

[02:16:11] Starting 'watch'...
[02:16:11] Starting test server on port 21113
[02:16:24] Starting unit tests
[02:16:24] Error: spawn node_modules.bin\mocha-phantomjs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:349:13)
[02:16:24] Mocha exited with code ENOENT
[02:16:24] Unit tests finished
[02:16:24] Tests failed
[02:16:27] Build complete
[02:16:27] Starting unit tests
[02:16:27] Error: spawn node_modules.bin\mocha-phantomjs ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:349:13)
[02:16:27] Mocha exited with code ENOENT
[02:16:27] Unit tests finished
[02:16:27] Tests failed

When I run code in NODE REPL:

**_The path is node_modules.bin\mocha-phantomjs**_

**Comment by tnedich** [comment]
Maybe there is some problem with path.

node_modules.bin\mocha-phantomjs

Should it be:

node_modules.bin\mocha-phantomjs

Attached are screenshots from my project folder if You mean about that when You say content of  .bin\mocha-phantomjs.

one.png  -  react-fluxthis-webpack-mocha-gulp\node_modules.bin
two.png -  react-fluxthis-webpack-mocha-gulp\node_modules\mocha-phantomjs

![one](https://cloud.githubusercontent.com/assets/6969501/7787649/f197e456-0216-11e5-81eb-840858082773.png)
![two](https://cloud.githubusercontent.com/assets/6969501/7787650/f26f941e-0216-11e5-863a-3631f8a189cc.png)

**Comment by mako-taco** [comment]
I don't have ready access to a windows machine. If you could fix this and PR it, I would really appreciate it. Sorry =\

**Comment by mako-taco** [comment]
Got to a windows box @tnedich and fixed the issue. The problem is that windows needed to run `mocha-phantonjs.cmd` instead of just `mocha-phantomjs`.
